---

- name: Prepare Jenkins partition
  win_shell: >
              Get-Disk |
              Where partitionstyle -eq "raw" |
              Initialize-Disk -PartitionStyle MBR -PassThru |
              New-Partition -DriveLetter J -UseMaximumSize |
              Format-Volume -FileSystem NTFS -NewFileSystemLabel "Jenkins" -Confirm:$false
