---

- name: Deploy controller VMs for testenv '{{ testenv_name }}'
  delegate_to: localhost
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ validate_certs }}"

    datacenter: "{{ datacenter_name }}"
    cluster: "{{ cluster_name }}"
    folder: "{{ testenv_folder }}"

    name: "{{ inventory_hostname_short }}"
    template: "{{ hostvars[inventory_hostname].template }}"
    annotation: "Ansible-created for {{ testenv_name }} environment"
    state: poweredon

    networks:
      - name: "{{ portgroup_mgmt }}"
      - name: "{{ portgroup_contrail }}"

    wait_for_ip_address: yes

  register: newvm

- debug:
    msg: "[{{ inventory_hostname }}]: SSH_HOST={{ ansible_ssh_host }}"

- name: Change hostname
  hostname:
    name: ds-demo-env-controller

- name: Update /etc/hosts
  template:
    src: hosts-controller.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Reboot host
  shell: reboot

- name: Wait for reboot
  wait_for:
    host: "{{ ansible_ssh_host }}"
    port: 22
    state: started
  connection: local
  become: no

# TODO: /etc/rabbitmq/rabbitmq-env.conf; template-contrail-controller into ds-demo-env-controller
# TODO: /etc/contrail/contrail-dns.conf; template-contrail-controller into ds-demo-env-controller
# TODO: /etc/contrail/contrail-control.conf; template-contrail-controller into ds-demo-env-controller

# TODO: remove BGP router from contrail;
#       add BGP router for the new hostname

# TODO: remove virtual router from contrail;
#       add virtual router based on new hostname

- name: Save VM info to inventory file '{{ vm_inventory_file }}'
  delegate_to: localhost
  lineinfile:
    path: "{{ vm_inventory_file }}"
    create: yes
    line: "{{ inventory_hostname }};{{ newvm.instance.hw_eth0.ipaddresses | ipv4 }};{{ newvm.instance.hw_product_uuid }}"
