---

- name: Deploy testbed VMs for testenv '{{ testenv_name }}' using API directly
  delegate_to: localhost
  shell: |
    '{{ script_path.path }}/provision_vm.py' \
      --host {{ vcenter_hostname }} \
      --user {{ vcenter_user }} \
      --password {{ vcenter_password }} \
      --datacenter {{ datacenter_name }} \
      --template {{ hostvars[inventory_hostname].template }} \
      --folder {{ testenv_folder }} \
      --name {{ inventory_hostname_short }} \
      --mgmt-network {{ portgroup_mgmt }} \
      --data-network {{ portgroup_contrail }} \
      --data-ip-address {{ hostvars[inventory_hostname].ip }} \
      --data-netmask {{ hostvars[inventory_hostname].netmask }} \
      --vm-username Administrator \
      --vm-password Contrail123!
