- name: Clone contrail-ansible-deployer repository
  git:
    repo: 'https://github.com/Juniper/contrail-ansible-deployer'
    dest: "{{ docker_provision_dir }}"
    version: ff44e8a4a61b8c2a7fd31e44e755ed4a14249490
    force: yes

- name: Install build dependencies
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
    - ansible

<<<<<<< HEAD
=======
- name: Set registry port
  set_fact:
    registry_port: "{{ docker_registry.port }}"
  when: registry_port is not defined

>>>>>>> 58a7fd1... JW-1433 : Adding roles contrail-ansible-deployer, kolla-provision-dockers and
- name: Copy hosts template
  template:
    src: inventory/hosts.j2
    dest: "{{ docker_provision_dir }}/inventory/hosts"

- name: Copy vars template
  template:
    src: "inventory/group_vars/{{ item }}.j2"
    dest: "{{ docker_provision_dir }}/inventory/group_vars/{{ item }}"
  with_items:
    - all.yml
    - container_hosts.yml

- name: ensure SSH key is generated
  command: ssh-keygen -t rsa -f /root/.ssh/id_rsa -N ''
  args:
    creates: /root/.ssh/id_rsa
  become: True
  become_user: root

- name: add key to authorized keys
  shell: |
    cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/id_rsa
    chmod 600 /root/.ssh/id_rsa.pub
    chmod 700 /root/.ssh
  become: True
  become_user: root

- name: Provision Contrail with deploy.yml playbook
  command: >
    ansible-playbook -i inventory/ playbooks/deploy.yml -v
  args:
    chdir: "{{ docker_provision_dir }}"
  environment:
    ANSIBLE_HOST_KEY_CHECKING: 'False'
    ANSIBLE_STDOUT_CALLBACK: debug
  become: True
  become_user: root

- name: Show the list of running containers
  command: docker ps -a
  become: True
  become_user: root

- name: Show processes
  command: ps aux --sort rss

- name: Show memory usage
  command: free -m

- name: cooldown
  wait_for:
    timeout: 120

- name: Drop caches to give the vrouter contiguous memory to allocate
  shell: "sync; echo 1 > /proc/sys/vm/drop_caches"
  become: True
  become_user: root

- name: wait for the vrouter initialization
  wait_for:
    host: github.com
    port: 443
    timeout: 3000
    delay: 60
    state: started

- name: Restart agent after vrouter startup
  command: docker restart {{ item }}
  become: True
  become_user: root
  with_items:
    - contrailvrouter_vrouter-agent_1
    - vrouter_vrouter-agent_1
  ignore_errors: true

- name: Show the list of running containers
  command: docker ps -a
  become: True
  become_user: root

- name: Agent cooldown
  wait_for:
    timeout: 120
