---

- hosts: localhost
  connection: local
  tasks:
  - name: Add controller to inventory
    add_host:
      name: masterController
      ansible_host: "{{ controllerIP }}"
      groups: controller

- hosts: masterController
  roles:
    - controller
